### ISSUE TITLE
Harness SecretText API

### ISSUE THREAD

**Issue by bennythejudge** [sullivtr/terraform-provider-graphql#28] opened 2021-04-19 20:55 UTC
Hi @sullivtr thanks for the provider.
This is not an issue per se but a request for help.
I am trying to use your provider with the Harness GraphQl API for secrets
https://docs.harness.io/article/omnfccj1n0-api-encrypted-text#before_you_begin
In particular I am trying a simple Get Secret by ID, I have the following in `main.tf` and in the dedicated query file.
I have tried many variations of the query, all give error.
The following gives this error when I run a `tf apply`:

```
 "query_response" = "{\"errors\":[{\"message\":\"Validation error of type UndefinedVariable: Undefined variable secretId @ 'secret'\",\"locations\":[{\"line\":3,\"column\":20}]}]}"
```

Could you help? Thanks

```
variable "harness_account_id" {
    type = string
}

variable "harness_api_token" {
    type = string
}

terraform {
  required_providers {
    graphql = {
      source = "sullivtr/graphql"
      version = "1.4.5"
    }
  }
}

provider "graphql" {
  url = "https://app.harness.io/gateway/api/graphql?accountId=${var.harness_account_id}"
  headers = {
      "x-api-key" = var.harness_api_token
  }
}

data "graphql_query" "get_secret_by_id" {

  query_variables = {
      "secretId"  = "A_VALID_ID"
  }

  query  = file("${path.module}/queries/getSecretTextById")
}

output "graphql_response_secret" {
  value = data.graphql_query.get_secret_by_id
}
```

```
query{
  secret(secretId: $secretId, secretType: ENCRYPTED_TEXT) {
    ... on EncryptedText {
      id
      name
      secretManagerId
      usageScope {
        appEnvScopes {
          application {
            filterType
            appId
          }
          environment {
            filterType
            envId
          }
        }
      }
      inheritScopesFromSM
      scopedToAccount
    }
  }
}
```

**Comment by sullivtr** [comment] 2021-04-19 21:34
Hi @bennythejudge. Thank you for reaching out. It has been a little while since I have used Harness's API (This provider was actually built to serve an automation use-case for harness), but it seems they still continue to return 200 responses with their errors. 

So looking at your query, I believe you will need to add args to the query like this (for example): 
```hcl
 query getSecretById($id: String!) {
  secret(secretId: $id, secretType: ENCRYPTED_TEXT) {
    ... on EncryptedText {
     ... # other stuff goes here
  }
}
```
Can you try to do something like this and let me know if it works? (NOTE: I just called the query method getSecretById but it can be called anything there)

**Comment by sullivtr** [comment] 2021-04-19 21:37
@bennythejudge This section of the GQL docs might be helpful in constructing your query with args as you are doing: https://graphql.org/learn/queries/#using-variables-inside-fragments

**Comment by bennythejudge** [comment] 2021-04-20 07:06
@sullivtr thanks for replying. The query you suggested is one of the many variations I have tried, here is the whole story:

- the `apply`:

```
tf apply --auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

graphql_response_secret = {
  "id" = "xxxxxxx"
  "query" = <<-EOT
   query getSecretById($secretId: String!) {
    secret(secretId: $secretId, secretType: ENCRYPTED_TEXT) {
      ... on EncryptedText {
        id
        name
        secretManagerId
        usageScope {
          appEnvScopes {
            application {
              filterType
              appId
            }
            environment {
              filterType
              envId
            }
          }
        }
        inheritScopesFromSM
        scopedToAccount
      }
    }
  }
  EOT
  "query_response" = "{\"errors\":[{\"message\":\"Exception while fetching data (/secret) : Invalid request: No secret exists with given input.\",\"locations\":[{\"line\":3,\"column\":3}],\"path\":[\"secret\"]}],\"data\":{\"secret\":null}}"
  "query_variables" = tomap({
    "secretId" = "zxzxzxzxzxxz"
  })
}
```

The secretId I am using exists, I can see that when I query the API interactively. I have noticed this bit in the above: 

```
  "query_response" = "{\"errors\":[{\"message\":\"Exception while fetching data (/secret) : Invalid request: No secret exists with given input.\",\"locations\":[{\"line\":3,\"column\":3}],\"path\":[\"secret\"]}],\"data\":{\"secret\":null}}"
```

Is the query not passing a secretId?

- the query:

```
 query getSecretById($secretId: String!) {
  secret(secretId: $secretId, secretType: ENCRYPTED_TEXT) {
    ... on EncryptedText {
      id
      name
      secretManagerId
      usageScope {
        appEnvScopes {
          application {
            filterType
            appId
          }
          environment {
            filterType
            envId
          }
        }
      }
      inheritScopesFromSM
      scopedToAccount
    }
  }
}
```

and the tf code:

```
data "graphql_query" "get_secret_by_id" {

  query_variables = {
      "secretId"  = "Z87iLR7MTUCGNj4Ch1IzgQ"
  }

  query  = file("${path.module}/queries/getSecretTextById")
}

output "graphql_response_secret" {
  value = data.graphql_query.get_secret_by_id
}
```

**Comment by sullivtr** [comment] 2021-04-20 15:37
In order to make sure the provider was correctly passing along the `query_variables`, I created this sample template using the free SpaceX GraphQL API:
```hcl
terraform {
  required_providers {
    graphql = {
      source = "sullivtr/graphql"
      version = "1.4.6"
    }
  }
}

provider "graphql" {
    url = "https://api.spacex.land/graphql"
}

data "graphql_query" "spacex_launch" {
  query_variables = {
      "id" = "109"
  }
  query = <<-EOT
  query GetLaunch($id: ID!) {
    launch(id: $id) {
      id
    }
  }
  EOT
}

output "spacex_launch_output" {
    value = data.graphql_query.spacex_launch
}
```
This example above operates as expected, passing an `id` of `109` to the query. Therefore, there are a few things that can be the problem. 
* Please ensure that when testing interactively in postman or insomnia, use the same exact query you use in your query file, and ensure it uses the same input variables.
* The secretId input in the harness query may not be of type String!. Their API is not known for returning descriptive errors, so consult their internal API explorer to ensure that variable type is set correctly on the query. (For example, in the spaceX example I have above, the id parameter is of a custom type `ID!`, so harness may be doing the same). 
* If all else fails, set your `query_variables = {}` to empty them, and then construct your query with a hardcoded value for the secretId directly in the query without using graphql input variables. If it still fails with the same error, that will tell us that the failure is happening with the Harness API interaction. 
* Please be sure that the secret does in fact exist with the provided secretId. IMO, for this type of automation, it may benefit you to use there `secretByName` query instead since the secret could be deleted and recreated at a later time, breaking your automation (This is what I did for secrets when automating the Harness API at my previous organization, and the organization continues doing so today).

At this time, I am not able to reproduce any issues passing the `query_variables` from the TF template to the actual query, so I am not sure how else I can be of assistance. Please consider some of my suggestions above, and let me know if any of them get you beyond this issue. 

NOTE: I am using version `v1.4.6` of the provider here, but there is no functional changes between `v1.4.5` and `v1.4.6`.

**Comment by bennythejudge** [comment] 2021-04-21 10:57
Thanks a lot.
The `data`  datasource works, I will add details at the bottom.
Now I am fighting with the `mutation` resource.
One question I have is: the `createSecret` mutation takes in input a `secret` which is a map. How do I do that with the `mutation_variables`? 

## working query:

```
data "graphql_query" "get_secret_by_name" {
  query_variables = {
      "name"  = "existing_secret"
  }
  query  = file("${path.module}/queries/getSecretTextByName")
}
```

content of `getSecretTextByName`
```
query GetSecretTextByName($name: String!) {
  secretByName(name: $name,secretType:ENCRYPTED_TEXT){
... on EncryptedText{
      id
      name
      secretManagerId
    }
 }
}
```

- output

```
tf output              
graphql_response_secret = "{\"data\":{\"secretByName\":{\"id\":\"some_long_id\",\"name\":\"secret_name\",\"secretManagerId\":\"not_so_longish_id\"}}}"
```

## mutation

```
resource "graphql_mutation" "secret_lifecycle" {
  # variables
  mutation_variables = {
      name = "new_secret_name"
      secret_type = "ENCRYPTED_TEXT"
      value = "some_value"
  }

  read_query_variables = {
      name = "new_secret_name"
  }

  compute_from_create = false

  compute_mutation_keys = {
  }

  create_mutation = file("./queries/createEncryptedTextSecret")
  update_mutation = file("./queries/updateSecretText")
  delete_mutation = file("./queries/deleteSecretText")
  read_query      = file("./queries/getSecretTextByName")
}
```

```
tf apply --auto-approve
graphql_mutation.secret_lifecycle: Creating...
graphql_mutation.secret_lifecycle: Creation complete after 1s [id=58777146]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

mutation_output = {
  "compute_from_create" = false
  "compute_mutation_keys" = tomap(null) /* of string */
  "computed_delete_operation_variables" = tomap({})
  "computed_read_operation_variables" = tomap({
    "name" = "new_secret_name"
  })
  "computed_update_operation_variables" = tomap({
    "name" = "new_secret_name"
    "secret_type" = "ENCRYPTED_TEXT"
    "value" = "some_value"
  })
  "create_mutation" = <<-EOT
  mutation($secret: CreateSecretInput!){
    createSecret(input: $secret){
      secret{
        id,
        name
        ... on EncryptedText{
          name
          secretManagerId
          id
        }
        usageScope{
          appEnvScopes{
            application{
              filterType
              appId
            }
            environment{
              filterType
              envId
            }
          }
        }
      }
    }
  }
  
  EOT
  "delete_mutation" = ""
  "delete_mutation_variables" = tomap(null) /* of string */
  "existing_hash" = "a_value"
  "id" = "a_value"
  "mutation_variables" = tomap({
    "name" = "new_secret_name"
    "secret_type" = "ENCRYPTED_TEXT"
    "value" = "some_value"
  })
  "query_response" = "{\"errors\":[{\"message\":\"Exception while fetching data (/secretByName) : Invalid request: No secret exists with given input.\",\"locations\":[{\"line\":3,\"column\":3}],\"path\":[\"secretByName\"]}],\"data\":{\"secretByName\":null}}"
  "read_query" = <<-EOT
  query GetSecretTextByName($name: String!) {
    secretByName(name: $name,secretType:ENCRYPTED_TEXT){
  ... on EncryptedText{
        id
        name
        secretManagerId
      }
   }
  }
  EOT
  "read_query_variables" = tomap({
    "name" = "new_secret_name"
  })
  "update_mutation" = ""
}
```

The mutation works fine in GraphiQl:

```
mutation ($secret: CreateSecretInput!) {
  createSecret(input: $secret) {
    secret {
      id
      name
      ... on EncryptedText {
        name
        secretManagerId
        id
      }
      usageScope {
        appEnvScopes {
          application {
            filterType
            appId
          }
          environment {
            filterType
            envId
          }
        }
      }
    }
  }
}
```

- query variables

```
{
  "secret": {
    "secretType": "ENCRYPTED_TEXT",
    "encryptedText": {
      "name": "azure-secrets1",
      "value": "000-azure-b22"
    }
  }
}
```

**Comment by sullivtr** [comment] 2021-04-21 15:39
This is a great question, @bennythejudge. Due to the way terraform variables work, it is not really possible to pass in the entire object as a variable into a mutation (in this case, a Harness `secret`). So you have to construct the mutation with the object inline on the mutation, passing in variables for specific fields. 

Here is an example of doing this:
```json
mutation CreateSecret($name: String!, $value: String!) {
  createSecret(input: {
      secretType: ENCRYPTED_TEXT,
      encryptedText: {
           name: $name,
           value: $value
     }
}) {
    secret {
      id
      name
      ... on EncryptedText {
        name
        secretManagerId
        id
      }
      usageScope {
        appEnvScopes {
          application {
            filterType
            appId
          }
          environment {
            filterType
            envId
          }
        }
      }
    }
  }
}
```
Your resource's mutation variables would look something like this:
```hcl
  mutation_variables = {
      name = "new_secret_name"
      value = "some_value"
  }
```
> NOTE: I have not tested the above mutation, but something similar to this should work, and you'll likely have to tweak that. Its the same thing I do in this provider's E2E test mutation here: https://github.com/sullivtr/terraform-provider-graphql/blob/master/testdata/createMutation#L2

**Comment by sullivtr** [comment] 2021-04-26 21:26
I believe I have answered all of your questions, and have provided enough information for you to move forward using this provider. Therefore, I am closing this issue. Feel free to open a new issue if you continue to need support.

**Closed by sullivtr** 2021-04-26 21:26 UTC
Labels: question
